name: Update Reviews Feed



jobs:
  update-reviews:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Fetch the JSON data from GAS
      - name: Fetch reviews JSON from GAS
        run: |
          curl -o reviews_feed.json "https://script.google.com/macros/s/AKfycbyOMSXiUHM6B84k6MxPraWxYaOo0SYV3Py8HsyMXWHLMLX8sC34jcHFhJsrVLp23k8/exec"

      # Step 3: Configure git and authenticate using the GitHub token
      - name: Configure git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push the updated feed
        run: |
          git add reviews_feed.json
          git commit -m "Update reviews feed"
          git push
        env:
          # Set the token to authenticate the GitHub Actions bot
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
